
enum PrinterStatus {
  CANCELLING = "CANCELLING",
  CLOSED_WITH_ERROR = "CLOSED_WITH_ERROR",
  RESERVED_CLOSED = "CLOSED",
  CONNECTING = "CONNECTING",
  DETECT_BAUDRATE = "DETECT_BAUDRATE",
  DETECT_SERIAL = "DETECT_SERIAL",
  ERROR = "ERROR",
  FINISHING = "FINISHING",
  NONE = "NONE",
  OFFLINE = "OFFLINE",
  OPEN_SERIAL = "OPEN_SERIAL",
  OPERATIONAL = "OPERATIONAL",
  PAUSED = "PAUSED",
  PAUSING = "PAUSING",
  PRINTING = "PRINTING",
  STARTING = "STARTING",
  TRANSFERING_FILE = "TRANSFERING_FILE",
  UNKNOWN = "UNKNOWN",
}
export { PrinterStatus };