
enum PrinterStatus {
  OPEN_SERIAL = "OPEN_SERIAL",
  CONNECTING = "CONNECTING",
  OPERATIONAL = "OPERATIONAL",
  PRINTING = "PRINTING",
  PAUSED = "PAUSED",
  RESERVED_CLOSED = "CLOSED",
  ERROR = "ERROR",
  UNKNOWN = "UNKNOWN",
  CLOSED_WITH_ERROR = "CLOSED_WITH_ERROR",
}
export { PrinterStatus };