name: Validate AsyncAPI Schemas

on:
  push:
    branches:
      - main
      - devel
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: WaleedAshraf/asyncapi-github-action@v0.0.8
        with:
          filepath: "2.4.0/printnanny-os.yml"
